id: P000130
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཀརྨ་ཆགས་མེད།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
  id: LEK-PHI-123
web_metadata:
  title:
    en: An Instruction on Mountain Dharma Practices
    bo: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས་བཞུགས་སོ།།
  collection:
    en: Lekshey Ling Philosophy Series–  Book 123
    bo: ལེགས་བཤད་གླིང་རིགས་པའི་གཞུང་ལུགས།–  དེབ། ༡༢༣
  author:
    en: Khedrub Karma Chagme
    bo: མཁས་གྲུབ་ཀརྨ་ཆགས་མེད།
  pusblisher:
    en: Lekshey Ling Philosophy Series
    bo: ཀརྨ་ལེགས་བཤད་གླིང།
  sku: LEK-PHI-123
  category:
    en: Retreat Manuals
    bo: མཚམས་དེབ་ཆུང་།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LEK-PHI-123.epub
  description:
    en: ''
    bo: ''
